languageCode = "en"
languageName = "English"
weight = 1
title = "opt-apps"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo-tall-thick-dark.png"
  secondaryLogo = "img/logo-tall-thick-light.png"
  description = "We build and integrate large-scale optimization applications for high performance use cases."
  copyright = "© { year } opt-apps.com | [Creative Commons License CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) unless otherwise noted | [Privacy](/privacy)"

[author]
  name = "Martin Laskowski"
  image = "img/martin.jpeg"
#  headline = "Likes brown Cherry MX switches, green jellybeans ..."
  bio = "Principal, Optimization Modeler"
  links = [
    { email = "mailto:martin@opt-apps.com" },
    { github = "https://github.com/MartinLaskowski" },
    { linkedin = "https://linkedin.com/in/martinlaskowski/" },
    { x-twitter = "https://twitter.com/martylasky" },
    { youtube = "https://www.youtube.com/@MartinLaskowski" },
#     { link = "https://link-to-some-website.com/" },
#     { codepen = "https://codepen.io/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
